export const adminNavigation = Object.freeze([
  { id: "dashboard", pageKey: "dashboard", pageName: "الرئيسية", path: "/admin/dashboard", iconKey: "dashboard" },
  { id: "suppliers", pageKey: "suppliers", pageName: "الموردون", path: "/admin/suppliers", iconKey: "suppliers" },
  { id: "inventory", pageKey: "inventory", pageName: "المواد الخام", path: "/admin/inventory", iconKey: "inventory" },
  { id: "warnings", pageKey: "warnings", pageName: "التحذيرات", path: "/admin/warnings", iconKey: "warnings" },
  { id: "purchases", pageKey: "purchases", pageName: "المشتريات", path: "/admin/purchases", iconKey: "purchases" },
  { id: "purchase-returns", pageKey: "purchase-returns", pageName: "المرتجعات", path: "/admin/returns", iconKey: "purchase-returns" },
  { id: "products", pageKey: "products", pageName: "المنتجات", path: "/admin/products", iconKey: "products" },
  { id: "orders-online", pageKey: "orders", pageName: "الأونلاين والتيك أواي", path: "/admin/orders/online", iconKey: "orders-online", section: "الطلبات" },
  { id: "orders-tables", pageKey: "tables", pageName: "طلبات الطاولات", path: "/admin/orders/tables", iconKey: "orders-tables", section: "الطلبات" },
  { id: "table-services", pageKey: "table-services", pageName: "خدمات الطاولات", path: "/admin/orders/table-services", iconKey: "table-services", section: "الطلبات" },
  { id: "orders-history", pageKey: "orders", pageName: "سجل الطلبات", path: "/admin/orders/history", iconKey: "orders-history", section: "الطلبات" },
  { id: "preparation", pageKey: "preparation", pageName: "التحضير", path: "/admin/orders/preparation", iconKey: "preparation", section: "الطلبات" },
  { id: "customers", pageKey: "customers", pageName: "العملاء", path: "/admin/customers", iconKey: "customers" },
  { id: "delegates", pageKey: "delegates", pageName: "المناديب", path: "/admin/delegates", iconKey: "delegates" },
  { id: "drawer", pageKey: "drawer", pageName: "الدرج", path: "/admin/drawer", iconKey: "drawer" },
  { id: "reports", pageKey: "reports", pageName: "التقارير المالية", path: "/admin/financial-reports", iconKey: "reports" },
  { id: "audit", pageKey: "audit", pageName: "سجل التدقيق", path: "/admin/audit", iconKey: "audit" },
  { id: "reviews", pageKey: "reviews", pageName: "التقييمات", path: "/admin/reviews", iconKey: "reviews" },
  { id: "employees", pageKey: "employees", pageName: "الموظفون", path: "/admin/employees", iconKey: "employees" },
]);
