import { useEffect,useRef,useState } from "react";
import { useNavigate } from "react-router-dom";
import { Plus,Search,Truck } from "lucide-react";
import { beginOperation,finishOperation } from "@/api/idempotency";
import { ServerPagination } from "@/shared/components";
import PageHeader from "@/shared/components/PageHeader/PageHeader";
import { deliveryApi } from "../api/delivery.api";
import "./DelegatesPage.css";
const msg=e=>e?.response?.data?.error?.messageAr||e?.response?.data?.message||e.message;
export default function DelegatesPage(){const nav=useNavigate(),scope=useRef("delegate:create");const[form,setForm]=useState({name:"",phone:"",maxActiveOrders:5}),[page,setPage]=useState(1),[search,setSearch]=useState(""),[data,setData]=useState({delegates:[],pageMeta:{}}),[error,setError]=useState(""),[saving,setSaving]=useState(false);const load=async()=>{try{setData(await deliveryApi.screen({page,limit:10,search:search.trim()||undefined}));setError("");}catch(e){setError(msg(e));}};useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[page,search]);const create=async e=>{e.preventDefault();setSaving(true);try{await deliveryApi.createDelegate({...form,maxActiveOrders:Number(form.maxActiveOrders)},beginOperation(scope.current));finishOperation(scope.current);setForm({name:"",phone:"",maxActiveOrders:5});await load();}catch(x){setError(msg(x));}finally{setSaving(false);}};return <div className="delegates-page"><PageHeader title="المناديب" breadcrumbs={["الإدارة","المناديب"]} icon={Truck}/><div className="delegates-content"><form className="delegate-form" onSubmit={create}><h2><Plus/> إضافة مندوب</h2><input required minLength={2} placeholder="اسم المندوب" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required minLength={7} placeholder="رقم الهاتف وواتساب" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input type="number" min="1" max="100" value={form.maxActiveOrders} onChange={e=>setForm({...form,maxActiveOrders:e.target.value})}/><button disabled={saving}>{saving?"جاري الحفظ...":"إضافة المندوب"}</button></form>{error&&<p role="alert" className="delegates-error">{error}</p>}<section className="delegates-list"><div className="delegates-list__header"><h2>قائمة المناديب ({data.summary?.total??0})</h2><label><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="بحث"/></label></div><div className="delegates-table-wrap"><table><thead><tr><th>المندوب</th><th>الهاتف</th><th>النشط</th><th>تم التوصيل</th><th>السعة</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{(data.delegates||[]).map(d=><tr key={d.id} onClick={()=>nav(`/admin/delegates/${d.id}`)}><td>{d.name}</td><td>{d.phone}</td><td>{d.activeOrderCount}</td><td>{d.deliveredCount}</td><td>{d.activeOrderCount}/{d.maxActiveOrders}</td><td><span className={`delegate-status ${String(d.status).toUpperCase() === "ACTIVE" ? "delegate-status--available" : "delegate-status--unavailable"}`}>{d.status}</span></td><td><button type="button" className="delegate-open-btn" onClick={(event) => { event.stopPropagation(); nav(`/admin/delegates/${d.id}`); }}>فتح</button></td></tr>)}</tbody></table></div><ServerPagination meta={data.pageMeta} label="مندوب" onPageChange={setPage}/></section></div></div>}
