import { useCallback,useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { ArrowRight,MessageCircle,Phone,Truck } from "lucide-react";
import { beginOperation,finishOperation } from "@/api/idempotency";
import PageHeader from "@/shared/components/PageHeader/PageHeader";
import { ordersApi } from "../../orders/api/orders.api";
import { deliveryApi } from "../api/delivery.api";
import { buildWhatsappInvoiceUrl } from "../utils/whatsapp";
import "./DelegateDetailsPage.css";
const msg=e=>e?.response?.data?.error?.messageAr||e?.response?.data?.message||e.message;
const labels={ASSIGNED:"تم الإسناد",IN_PROGRESS:"خرج للتوصيل",DELIVERED:"تم التسليم",FAILED:"تعذر التوصيل",RETURNED:"عاد للمحل",REASSIGNED:"نقل لمندوب آخر"};
export default function DelegateDetailsPage(){const{id}=useParams(),nav=useNavigate();const[data,setData]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState("");const load=useCallback(async()=>{try{setData(await deliveryApi.delegate(id));setError("");}catch(e){setError(msg(e));}},[id]);useEffect(()=>{load();},[load]);const run=async(a,fn)=>{setBusy(a.id);try{const s=`delivery:${a.id}:${fn.name}`;await fn(beginOperation(s));finishOperation(s);await load();}catch(e){setError(msg(e));}finally{setBusy("");}};const reason=()=>window.prompt("اكتب السبب بالتفصيل")?.trim();const whatsapp=async a=>{const popup=window.open("about:blank","_blank");try{const print=await ordersApi.print(a.orderId);const url=buildWhatsappInvoiceUrl(data.delegate.phone,print);if(!url)throw new Error("رقم واتساب غير صالح");await run(a,key=>deliveryApi.recordWhatsapp(a.id,{expectedVersion:a.version},key));popup.location.href=url;}catch(e){popup?.close();setError(msg(e));}};const actionButtons=a=><div className="dd-actions">{["ASSIGNED","IN_PROGRESS"].includes(a.status)&&<button disabled={busy===a.id} onClick={()=>{const delegateId=window.prompt("معرف المندوب الجديد");const r=delegateId&&reason();if(r)run(a,key=>deliveryApi.reassign(a.id,{delegateId,reason:r,expectedVersion:a.version},key));}}>نقل لمندوب آخر</button>}{["ASSIGNED","IN_PROGRESS"].includes(a.status)&&<button disabled={busy===a.id} onClick={()=>run(a,key=>deliveryApi.deliver(a.id,{expectedVersion:a.version},key))}>تأكيد الاستلام</button>}{a.status==="IN_PROGRESS"&&<><button disabled={busy===a.id} onClick={()=>{const r=reason();if(r)run(a,key=>deliveryApi.failed(a.id,{reason:r,expectedVersion:a.version},key));}}>تعذر التوصيل</button></>}{["IN_PROGRESS","FAILED"].includes(a.status)&&<button disabled={busy===a.id} onClick={()=>{const r=reason();if(r)run(a,key=>deliveryApi.returned(a.id,{reason:r,expectedVersion:a.version},key));}}>عودة للمحل</button>}{a.status==="DELIVERED"&&Number(a.cashExpected)>Number(a.cashSettledTotal)&&<button disabled={busy===a.id} onClick={()=>run(a,key=>deliveryApi.settle(a.id,{expectedVersion:a.version},key))}>تسوية الكاش</button>}<button onClick={()=>whatsapp(a)}><MessageCircle size={15}/> إرسال الفاتورة واتساب</button><button onClick={()=>nav(`/admin/orders/busy/online/${a.orderId}`)}>فتح الطلب</button></div>;
if(!data)return <div className="delegate-details-page"><PageHeader title="المندوب"/>{error||"جاري التحميل..."}</div>;const d=data.delegate;return <div className="delegate-details-page"><PageHeader title={`${d.name} — المندوب`} breadcrumbs={["الإدارة","المناديب",d.name]} icon={Truck}/><div className="delegate-details-content"><button className="dd-back" onClick={()=>nav("/admin/delegates")}><ArrowRight/> رجوع</button>{error&&<p role="alert" className="dd-error">{error}</p>}<section className="dd-profile"><h2>{d.name}</h2><p><Phone size={16}/> {d.phone}</p><p>الحالة: {d.status} — الطلبات النشطة: {d.activeOrderCount}/{d.maxActiveOrders} — تم التوصيل: {d.deliveredCount}</p><div className="customer-stats"><span>العهدة المتوقعة: {data.cashLedger?.expected||0} ج.م</span><span>المسوى: {data.cashLedger?.settled||0} ج.م</span><strong>المتبقي: {data.cashLedger?.outstanding||0} ج.م</strong></div></section><section className="dd-orders"><h2>الطلبات النشطة</h2>{(data.activeOrders||[]).map(a=><article key={a.id} className="dd-profile"><h3>{a.assignmentNo} — {labels[a.status]}</h3><p>الطلب: {a.orderId} | الكاش: {a.cashExpected} ج.م</p>{actionButtons(a)}</article>)}{!(data.activeOrders||[]).length&&<p>لا توجد طلبات نشطة</p>}<h2>آخر العمليات</h2><div className="dd-table-wrap"><table><thead><tr><th>رقم الإسناد</th><th>الحالة</th><th>المتوقع</th><th>المسوى</th><th>السبب</th><th>الإجراءات</th></tr></thead><tbody>{(data.history||[]).map(a=><tr key={a.id}><td>{a.assignmentNo}</td><td>{labels[a.status]||a.status}</td><td>{a.cashExpected} ج.م</td><td>{a.cashSettledTotal} ج.م</td><td>{a.reason||"—"}</td><td>{actionButtons(a)}</td></tr>)}</tbody></table></div></section></div></div>}


