import { useEffect,useRef,useState } from "react";
import { useNavigate } from "react-router-dom";
import { Search,Users } from "lucide-react";
import { beginOperation,finishOperation } from "@/api/idempotency";
import { ServerPagination } from "@/shared/components";
import PageHeader from "@/shared/components/PageHeader/PageHeader";
import CustomerForm from "../components/CustomerForm";
import { customersApi } from "../api/customers.api";
import "../styles/CustomersPage.css";
const msg=e=>e?.response?.data?.error?.messageAr||e?.response?.data?.message||e.message;
export default function CustomersPage(){const nav=useNavigate(),scope=useRef("customer:create");const[page,setPage]=useState(1),[search,setSearch]=useState(""),[data,setData]=useState({customers:[],pageMeta:{}}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false);const load=async()=>{setLoading(true);try{setData(await customersApi.screen({page,limit:10,search:search.trim()||undefined}));setError("");}catch(e){setError(msg(e));}finally{setLoading(false);}};useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[page,search]);const create=async payload=>{setSaving(true);try{await customersApi.create(payload,beginOperation(scope.current));finishOperation(scope.current);await load();}catch(e){setError(msg(e));throw e;}finally{setSaving(false);}};return <div className="customers-page"><PageHeader title="إدارة العملاء" breadcrumbs={["الرئيسية","العملاء"]}/><div className="customers-form-section"><h3>تسجيل عميل جديد</h3><CustomerForm onSubmit={create} busy={saving}/></div><div className="customers-list-section"><div className="customers-list-head"><h3><Users size={18}/> العملاء ({data.summary?.total??0})</h3><div className="customers-search"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="بحث بالاسم أو الهاتف"/></div></div>{error&&<p role="alert" className="delegates-error">{error}</p>}{loading?<p>جاري التحميل...</p>:<div className="customers-table-wrap"><table className="customers-table"><thead><tr><th>الاسم</th><th>الهاتف</th><th>العنوان</th><th>الحالة</th><th>الطلبات</th><th>المكتملة</th><th>إجمالي المشتريات</th><th>الإجراءات</th></tr></thead><tbody>{(data.customers||[]).map(c=><tr key={c.id} onClick={()=>nav(`/admin/customers/${c.id}`)}><td>{c.name}</td><td>{c.phone}</td><td>{c.address||"—"}</td><td><span className={`customer-status customer-status--${String(c.status || "").toLowerCase()}`}>{c.status}</span></td><td>{c.orderCount}</td><td>{c.completedOrderCount}</td><td>{Number(c.lifetimeValue||0).toLocaleString("ar-EG")} ج.م</td><td><button type="button" className="customer-open-btn" onClick={(event) => { event.stopPropagation(); nav(`/admin/customers/${c.id}`); }}>فتح</button></td></tr>)}</tbody></table></div>}<ServerPagination meta={data.pageMeta} disabled={loading} label="عميل" onPageChange={setPage}/></div></div>}
