import { useEffect,useRef,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { ArrowRight,Pencil,Printer } from "lucide-react";
import { beginOperation,finishOperation } from "@/api/idempotency";
import PageHeader from "@/shared/components/PageHeader/PageHeader";
import CustomerForm from "../components/CustomerForm";
import { customersApi } from "../api/customers.api";
import { ordersApi } from "../../orders/api/orders.api";
import "../styles/CustomerDetailsPage.css";
const msg=e=>e?.response?.data?.error?.messageAr||e?.response?.data?.message||e.message;
export default function CustomerDetailsPage(){const{id}=useParams(),nav=useNavigate(),scope=useRef(`customer:update:${id}`);const[data,setData]=useState(null),[editing,setEditing]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=async()=>{try{setData(await customersApi.details(id));setError("");}catch(e){setError(msg(e));}};useEffect(()=>{load();},[id]);const update=async payload=>{setBusy(true);try{await customersApi.update(id,{name:payload.name,address:payload.address||null,...(payload.socialLinks?{socialLinks:payload.socialLinks}:{}),expectedVersion:data.customer.version},beginOperation(scope.current));finishOperation(scope.current);setEditing(false);await load();}catch(e){setError(msg(e));throw e;}finally{setBusy(false);}};const print=async orderId=>{try{const d=await ordersApi.print(orderId);const w=window.open("","_blank");w.document.write(`<pre dir="rtl">${JSON.stringify(d,null,2).replaceAll("<","&lt;")}</pre>`);w.document.close();w.print();}catch(e){setError(msg(e));}};if(!data)return <div className="customer-details-page"><PageHeader title="تفاصيل العميل"/>{error||"جاري التحميل..."}</div>;const c=data.customer,orders=data.orders?.items||data.orders||[],reviews=data.reviews?.items||data.reviews||[];return <div className="customer-details-page"><PageHeader title={`تفاصيل العميل - ${c.name}`} breadcrumbs={["الرئيسية","العملاء",c.name]}/><button className="btn-back" onClick={()=>nav("/admin/customers")}><ArrowRight/> رجوع</button>{error&&<p role="alert">{error}</p>}<section className="customer-info-card"><div className="customer-info-header"><h2>{c.name}</h2><button className="customer-edit-btn" onClick={()=>setEditing(!editing)}><Pencil size={15}/> تعديل</button></div><div className="customer-info-body"><p>الهاتف: {c.phone}</p><p>العنوان: {c.address||"—"}</p><p>الحالة: {c.status}</p><p>الطلبات: {c.orderCount} — المكتملة: {c.completedOrderCount}</p><p>إجمالي المشتريات: {Number(c.lifetimeValue||0).toLocaleString("ar-EG")} ج.م</p></div></section>{editing&&<CustomerForm initial={c} busy={busy} onCancel={()=>setEditing(false)} onSubmit={update}/>}<section className="customer-orders-section"><h3>طلبات العميل</h3><div className="customer-orders-table-wrapper"><table className="customer-orders-table"><thead><tr><th>الطلب</th><th>الحالة</th><th>الإجمالي</th><th>التاريخ</th><th>الفاتورة</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.orderNumber}</td><td>{o.status}</td><td>{Number(o.total||o.totals?.total||0).toLocaleString("ar-EG")} ج.م</td><td>{o.createdAt?new Date(o.createdAt).toLocaleString("ar-EG"):"—"}</td><td><button onClick={()=>print(o.id)}><Printer size={15}/> طباعة</button></td></tr>)}</tbody></table></div></section><section className="customer-feedback-section"><h3>التقييمات ({reviews.length})</h3>{reviews.length?reviews.map(r=><article key={r.id}><strong>{r.rating}/5</strong><p>{r.comment||"بدون تعليق"}</p></article>):<p>لا توجد تقييمات</p>}</section></div>}

